services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    volumes:
    - ./docker/peercfg:/etc/hyperledger/peercfg
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    volumes:
    - ./docker/peercfg:/etc/hyperledger/peercfg
    - ${DOCKER_SOCK}:/host/var/run/docker.sock
  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    volumes:
    - ./docker/peercfg:/etc/hyperledger/peercfg
    - ${DOCKER_SOCK}:/host/var/run/docker.sock
  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    volumes:
    - ./docker/peercfg:/etc/hyperledger/peercfg
    - ${DOCKER_SOCK}:/host/var/run/docker.sock
  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    volumes:
    - ./docker/peercfg:/etc/hyperledger/peercfg
    - ${DOCKER_SOCK}:/host/var/run/docker.sock
  peer2.org1.example.com:
    container_name: peer2.org1.example.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    volumes:
    - ./docker/peercfg:/etc/hyperledger/peercfg
    - ${DOCKER_SOCK}:/host/var/run/docker.sock
  peer2.org2.example.com:
    container_name: peer2.org2.example.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    volumes:
    - ./docker/peercfg:/etc/hyperledger/peercfg
    - ${DOCKER_SOCK}:/host/var/run/docker.sock
version: '3.7'
